apiVersion: apps/v1
kind: Deployment
metadata:
  name: biplabInsurence
  labels:
    app: biplab-insurence-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: biplab-insurence-app
  template:
    metadata:
      labels:
        app: biplab-insurence-app
    spec:
      containers:
      - name: biplab-insurence-container
        image: biplabstudy/biplab-insurence-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: biplab-insurence-app
  labels:
    app: biplab-insurence-app
spec:
  selector:
    app: biplab-insurence-app

  type: NodePort
  ports:
  - nodePort: 30110
    port: 81
    targetPort: 8082
